name: flutter_rust_sip
description: "Use PJSIP in Flutter via Rust FFI"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_my_app:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  freezed_annotation: ^2.0.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

dev_dependencies:
  freezed: ^2.0.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
